### ISSUE TITLE
Ubuntu Linux; Invalid pointer on exit

### ISSUE THREAD

**Issue by select-this** [fallahn/pseuthe#5]
Looks like something funky is going on with the message bus during shutdown (by pressing the `quit` button, as opposed to a SIGINT for example):

`*** Error in '/home/darren.ferrie/workspace/pseuthe/pseuthe/pseuthe': free(): invalid pointer: 0x0000000001313120 ***`

I tested this 5 times and got exactly the same result every time, so seems to be pretty deterministic behaviour, at least in debug mode. Release mode produces a different, much less specific error that may well go away once this (and anything else like it) is solved.

You get a nice lovely stack trace, which I've provided at the bottom, but here's the pertinent bits:

```
#14 0x000000000054e3e5 in MessageBus::send (this=0x7fffffffdcd8, m=...) at /home/darren.ferrie/workspace/pseuthe/pseuthe/src/MessageBus.cpp:45
45      (m_polling) ? m_deferredMessages.push(m) : m_messages.push(m);
```

https://github.com/fallahn/pseuthe/blob/master/pseuthe/src/MessageBus.cpp#L45

```
void MessageBus::send(const Message& m)
{
    (m_polling) ? m_deferredMessages.push(m) : m_messages.push(m);
}
```

`m_polling` is set to false here.

I'm short on time so unable to investigate fully tonight, and I'm not sure what my schedule for the rest of the week is, but if you don't get time to take a look then I can do some more investigation into the issue if you'd like. My first guess would be some form of destruction order issue, considering so many parts have references to the message bus, but I haven't fully scrutinised the evidence yet.

Full stack trace:

```
#0  0x00007ffff5f96267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff5f97eca in __GI_abort () at abort.c:89
#2  0x00007ffff5fd9c53 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff60f21a8 "*** Error in '%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff5fe1c69 in malloc_printerr (ptr=<optimised out>, str=0x7ffff60ee2fa "free(): invalid pointer", action=1) at malloc.c:4965
#4  _int_free (av=<optimised out>, p=<optimised out>, have_lock=0) at malloc.c:3834
#5  0x00007ffff5fe589c in __GI___libc_free (mem=<optimised out>) at malloc.c:2950
#6  0x0000000000501768 in __gnu_cxx::new_allocator<Message*>::deallocate (this=0x7fffffffd157, __p=0x1313120) at /usr/include/c++/5/ext/new_allocator.h:110
#7  0x0000000000501580 in std::allocator_traits<std::allocator<Message*> >::deallocate (__a=..., __p=0x1313120, __n=8) at /usr/include/c++/5/bits/alloc_traits.h:386
#8  0x00000000005012b3 in std::_Deque_base<Message, std::allocator<Message> >::_M_deallocate_map (this=0x7fffffffdcd8, __p=0x1313120, __n=8) at /usr/include/c++/5/bits/stl_deque.h:622
#9  0x000000000054f323 in std::deque<Message, std::allocator<Message> >::_M_reallocate_map (this=0x7fffffffdcd8, __nodes_to_add=1, __add_at_front=false) at /usr/include/c++/5/bits/deque.tcc:935
#10 0x000000000054ef6b in std::deque<Message, std::allocator<Message> >::_M_reserve_map_at_back (this=0x7fffffffdcd8, __nodes_to_add=1) at /usr/include/c++/5/bits/stl_deque.h:2117
#11 0x000000000054eb20 in std::deque<Message, std::allocator<Message> >::_M_push_back_aux<Message const&> (this=0x7fffffffdcd8) at /usr/include/c++/5/bits/deque.tcc:470
#12 0x000000000054e729 in std::deque<Message, std::allocator<Message> >::push_back (this=0x7fffffffdcd8, __x=...) at /usr/include/c++/5/bits/stl_deque.h:1525
#13 0x000000000054e539 in std::queue<Message, std::deque<Message, std::allocator<Message> > >::push (this=0x7fffffffdcd8, __x=...) at /usr/include/c++/5/bits/stl_queue.h:216
#14 0x000000000054e3e5 in MessageBus::send (this=0x7fffffffdcd8, m=...) at /home/darren.ferrie/workspace/pseuthe/pseuthe/src/MessageBus.cpp:45
#15 0x0000000000524746 in Component::~Component (this=0x1f1d510, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/src/Component.cpp:46
#16 0x0000000000533e64 in PhysicsComponent::~PhysicsComponent (this=0x1f1d510, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/PhysicsComponent.hpp:54
#17 0x0000000000533e98 in PhysicsComponent::~PhysicsComponent (this=0x1f1d510, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/PhysicsComponent.hpp:54
#18 0x000000000051c4e2 in std::default_delete<Component>::operator() (this=0x4340df8, __ptr=0x1f1d510) at /usr/include/c++/5/bits/unique_ptr.h:76
#19 0x000000000051c42b in std::unique_ptr<Component, std::default_delete<Component> >::~unique_ptr (this=0x4340df8, __in_chrg=<optimised out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#20 0x000000000051c361 in std::_Destroy<std::unique_ptr<Component, std::default_delete<Component> > > (__pointer=0x4340df8) at /usr/include/c++/5/bits/stl_construct.h:93
#21 0x000000000051c2c5 in std::_Destroy_aux<false>::__destroy<std::unique_ptr<Component, std::default_delete<Component> >*> (__first=0x4340df8, __last=0x4340e18) at /usr/include/c++/5/bits/stl_construct.h:103
#22 0x000000000051c1e2 in std::_Destroy<std::unique_ptr<Component, std::default_delete<Component> >*> (__first=0x4340df0, __last=0x4340e18) at /usr/include/c++/5/bits/stl_construct.h:126
#23 0x000000000051c019 in std::_Destroy<std::unique_ptr<Component, std::default_delete<Component> >*, std::unique_ptr<Component, std::default_delete<Component> > > (__first=0x4340df0, __last=0x4340e18) at /usr/include/c++/5/bits/stl_construct.h:151
#24 0x000000000051be6f in std::vector<std::unique_ptr<Component, std::default_delete<Component> >, std::allocator<std::unique_ptr<Component, std::default_delete<Component> > > >::~vector (this=0x1f1cb88, __in_chrg=<optimised out>) at /usr/include/c++/5/bits/stl_vector.h:424
#25 0x000000000051bc5a in Entity::~Entity (this=0x1f1caa0, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/Entity.hpp:52
#26 0x000000000051bcca in Entity::~Entity (this=0x1f1caa0, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/Entity.hpp:52
#27 0x000000000051bd09 in std::default_delete<Entity>::operator() (this=0x1f25aa0, __ptr=0x1f1caa0) at /usr/include/c++/5/bits/unique_ptr.h:76
#28 0x000000000051b785 in std::unique_ptr<Entity, std::default_delete<Entity> >::~unique_ptr (this=0x1f25aa0, __in_chrg=<optimised out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#29 0x000000000051b421 in std::_Destroy<std::unique_ptr<Entity, std::default_delete<Entity> > > (__pointer=0x1f25aa0) at /usr/include/c++/5/bits/stl_construct.h:93
#30 0x000000000051ada3 in std::_Destroy_aux<false>::__destroy<std::unique_ptr<Entity, std::default_delete<Entity> >*> (__first=0x1f25aa0, __last=0x1f25ae8) at /usr/include/c++/5/bits/stl_construct.h:103
#31 0x000000000051a5ba in std::_Destroy<std::unique_ptr<Entity, std::default_delete<Entity> >*> (__first=0x1f25a50, __last=0x1f25ae8) at /usr/include/c++/5/bits/stl_construct.h:126
#32 0x0000000000519139 in std::_Destroy<std::unique_ptr<Entity, std::default_delete<Entity> >*, std::unique_ptr<Entity, std::default_delete<Entity> > > (__first=0x1f25a50, __last=0x1f25ae8) at /usr/include/c++/5/bits/stl_construct.h:151
#33 0x0000000000516e8d in std::vector<std::unique_ptr<Entity, std::default_delete<Entity> >, std::allocator<std::unique_ptr<Entity, std::default_delete<Entity> > > >::~vector (this=0x158a318, __in_chrg=<optimised out>) at /usr/include/c++/5/bits/stl_vector.h:424
#34 0x000000000051bc36 in Entity::~Entity (this=0x158a200, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/Entity.hpp:52
#35 0x000000000051bcca in Entity::~Entity (this=0x158a200, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/Entity.hpp:52
#36 0x000000000051bd09 in std::default_delete<Entity>::operator() (this=0x13b34b0, __ptr=0x158a200) at /usr/include/c++/5/bits/unique_ptr.h:76
#37 0x000000000051b785 in std::unique_ptr<Entity, std::default_delete<Entity> >::~unique_ptr (this=0x13b34b0, __in_chrg=<optimised out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#38 0x000000000051b421 in std::_Destroy<std::unique_ptr<Entity, std::default_delete<Entity> > > (__pointer=0x13b34b0) at /usr/include/c++/5/bits/stl_construct.h:93
#39 0x000000000051ada3 in std::_Destroy_aux<false>::__destroy<std::unique_ptr<Entity, std::default_delete<Entity> >*> (__first=0x13b34b0, __last=0x13b34c0) at /usr/include/c++/5/bits/stl_construct.h:103
#40 0x000000000051a5ba in std::_Destroy<std::unique_ptr<Entity, std::default_delete<Entity> >*> (__first=0x13b3490, __last=0x13b34c0) at /usr/include/c++/5/bits/stl_construct.h:126
#41 0x0000000000519139 in std::_Destroy<std::unique_ptr<Entity, std::default_delete<Entity> >*, std::unique_ptr<Entity, std::default_delete<Entity> > > (__first=0x13b3490, __last=0x13b34c0) at /usr/include/c++/5/bits/stl_construct.h:151
#42 0x0000000000516e8d in std::vector<std::unique_ptr<Entity, std::default_delete<Entity> >, std::allocator<std::unique_ptr<Entity, std::default_delete<Entity> > > >::~vector (this=0x13ac868, __in_chrg=<optimised out>) at /usr/include/c++/5/bits/stl_vector.h:424
#43 0x000000000051418a in Scene::~Scene (this=0x13ac860, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/Scene.hpp:56
#44 0x000000000051447a in GameState::~GameState (this=0x13ac790, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/GameState.hpp:54
#45 0x00000000005144ba in GameState::~GameState (this=0x13ac790, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/GameState.hpp:54
#46 0x000000000050197e in std::default_delete<State>::operator() (this=0x1b63740, __ptr=0x13ac790) at /usr/include/c++/5/bits/unique_ptr.h:76
#47 0x0000000000501833 in std::unique_ptr<State, std::default_delete<State> >::~unique_ptr (this=0x1b63740, __in_chrg=<optimised out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#48 0x0000000000501639 in std::_Destroy<std::unique_ptr<State, std::default_delete<State> > > (__pointer=0x1b63740) at /usr/include/c++/5/bits/stl_construct.h:93
#49 0x00000000005013fd in std::_Destroy_aux<false>::__destroy<std::unique_ptr<State, std::default_delete<State> >*> (__first=0x1b63740, __last=0x1b63750) at /usr/include/c++/5/bits/stl_construct.h:103
#50 0x000000000050111e in std::_Destroy<std::unique_ptr<State, std::default_delete<State> >*> (__first=0x1b63740, __last=0x1b63750) at /usr/include/c++/5/bits/stl_construct.h:126
#51 0x0000000000500cc7 in std::_Destroy<std::unique_ptr<State, std::default_delete<State> >*, std::unique_ptr<State, std::default_delete<State> > > (__first=0x1b63740, __last=0x1b63750) at /usr/include/c++/5/bits/stl_construct.h:151
#52 0x0000000000500895 in std::vector<std::unique_ptr<State, std::default_delete<State> >, std::allocator<std::unique_ptr<State, std::default_delete<State> > > >::~vector (this=0x7fffffffdac8, __in_chrg=<optimised out>) at /usr/include/c++/5/bits/stl_vector.h:424
#53 0x00000000005002fa in StateStack::~StateStack (this=0x7fffffffdac8, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/StateStack.hpp:56
#54 0x0000000000500416 in App::~App (this=0x7fffffffd880, __in_chrg=<optimised out>) at /home/darren.ferrie/workspace/pseuthe/pseuthe/include/App.hpp:81
#55 0x0000000000500078 in main () at /home/darren.ferrie/workspace/pseuthe/pseuthe/src/main.cpp:40
```

**Comment by fallahn** [comment]
You, sir, are a gent. Thank you. I shall study this carefully :)

**Comment by fallahn** [comment]
I _think_ 1ce7f0ccdc415b1d564a2cc3c16b79d1c7176c6c fixed this - I certainly don't get the error output to the terminal when closing the game any more. I do still get the occasional lockup when starting the game, which I now think is unrelated. Could you possibly test to confirm? Thanks

**Comment by select-this** [comment]
Yup, looks like that's done the job; 10 tests (5 in debug, 5 in release) and 100% success rate.

I'll test on the machine that originally had the issue just to make sure, but I'm pretty convinced that this bug has been squashed.

**Comment by fallahn** [comment]
Woo! Thanks
